# shell-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: shell-service
  replicas: 1
  template:
    metadata:
      labels:
        run: shell-service
    spec:
      containers:
        - name: shell-service
          image: svilgelm/shell-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: "http://event-broker.keptn.svc.cluster.local/keptn"
---
apiVersion: v1
kind: Service
metadata:
  name: shell-service
  namespace: keptn
  labels:
    run: shell-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: shell-service
---
## shell-service: sh.keptn.events.deployment-finished
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-service-deployment-distributor
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: "nats://keptn-nats-cluster"
            - name: PUBSUB_TOPIC
              value: "sh.keptn.events.deployment-finished"
            - name: PUBSUB_RECIPIENT
              value: "shell-service"
